/*
Pappers API

L'API de Pappers vous permet de récupérer des informations et documents sur les entreprises françaises à partir de leur numéro SIREN ou SIRET.  Vous devez indiquer votre clé d'API dans les requêtes, soit via le header `api-key`, soit (déconseillé) en utilisant le paramètre query `api_token`.  L'URL d'accès à l'API est https://api.pappers.fr/v2/  Lien vers la documentation de la V3 : https://www.pappers.fr/api/documentation/v3  Lien vers la documentation de l'API internationale : https://www.pappers.in/api/documentation  L'historique des modifications (changelog) est accessible à l'url suivante : https://www.pappers.fr/api/changelog 

API version: 2.16.0
Contact: support@pappers.fr
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the Labels type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Labels{}

// Labels struct for Labels
type Labels struct {
	// Nom du label.
	Nom *string `json:"nom,omitempty"`
	// Label RGE seulement : Liste des certificats.
	Certificats []string `json:"certificats,omitempty"`
	// Label QUALIOPI seulement : Liste des spécialités.
	Specialites []string `json:"specialites,omitempty"`
	// Label EGALITE seulement : Liste des notes.
	Notes []string `json:"notes,omitempty"`
	// Label ORIAS et CCI seulement : Numéro d'immatriculation ORIAS ou CCI. Uniquement présent si demandé avec le champ supplémentaire `label:orias` ou `label:cci`.
	NumeroImmatriculation *string `json:"numero_immatriculation,omitempty"`
	// Label ORIAS seulement : Liste des inscriptions ORIAS. Uniquement présent si demandé avec le champ supplémentaire `label:orias`.
	Inscriptions []LabelsBaseInscriptionsInner `json:"inscriptions,omitempty"`
	// Label CCI seulement : Liste des mentions.
	Mentions []string `json:"mentions,omitempty"`
	// Nombre d'établissements concernés par le label, dans le cas d'un label lié aux établissements. Null sinon.
	NbEtablissementsConcernes *int32 `json:"nb_etablissements_concernes,omitempty"`
}

// NewLabels instantiates a new Labels object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLabels() *Labels {
	this := Labels{}
	return &this
}

// NewLabelsWithDefaults instantiates a new Labels object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLabelsWithDefaults() *Labels {
	this := Labels{}
	return &this
}

// GetNom returns the Nom field value if set, zero value otherwise.
func (o *Labels) GetNom() string {
	if o == nil || IsNil(o.Nom) {
		var ret string
		return ret
	}
	return *o.Nom
}

// GetNomOk returns a tuple with the Nom field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Labels) GetNomOk() (*string, bool) {
	if o == nil || IsNil(o.Nom) {
		return nil, false
	}
	return o.Nom, true
}

// HasNom returns a boolean if a field has been set.
func (o *Labels) HasNom() bool {
	if o != nil && !IsNil(o.Nom) {
		return true
	}

	return false
}

// SetNom gets a reference to the given string and assigns it to the Nom field.
func (o *Labels) SetNom(v string) {
	o.Nom = &v
}

// GetCertificats returns the Certificats field value if set, zero value otherwise.
func (o *Labels) GetCertificats() []string {
	if o == nil || IsNil(o.Certificats) {
		var ret []string
		return ret
	}
	return o.Certificats
}

// GetCertificatsOk returns a tuple with the Certificats field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Labels) GetCertificatsOk() ([]string, bool) {
	if o == nil || IsNil(o.Certificats) {
		return nil, false
	}
	return o.Certificats, true
}

// HasCertificats returns a boolean if a field has been set.
func (o *Labels) HasCertificats() bool {
	if o != nil && !IsNil(o.Certificats) {
		return true
	}

	return false
}

// SetCertificats gets a reference to the given []string and assigns it to the Certificats field.
func (o *Labels) SetCertificats(v []string) {
	o.Certificats = v
}

// GetSpecialites returns the Specialites field value if set, zero value otherwise.
func (o *Labels) GetSpecialites() []string {
	if o == nil || IsNil(o.Specialites) {
		var ret []string
		return ret
	}
	return o.Specialites
}

// GetSpecialitesOk returns a tuple with the Specialites field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Labels) GetSpecialitesOk() ([]string, bool) {
	if o == nil || IsNil(o.Specialites) {
		return nil, false
	}
	return o.Specialites, true
}

// HasSpecialites returns a boolean if a field has been set.
func (o *Labels) HasSpecialites() bool {
	if o != nil && !IsNil(o.Specialites) {
		return true
	}

	return false
}

// SetSpecialites gets a reference to the given []string and assigns it to the Specialites field.
func (o *Labels) SetSpecialites(v []string) {
	o.Specialites = v
}

// GetNotes returns the Notes field value if set, zero value otherwise.
func (o *Labels) GetNotes() []string {
	if o == nil || IsNil(o.Notes) {
		var ret []string
		return ret
	}
	return o.Notes
}

// GetNotesOk returns a tuple with the Notes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Labels) GetNotesOk() ([]string, bool) {
	if o == nil || IsNil(o.Notes) {
		return nil, false
	}
	return o.Notes, true
}

// HasNotes returns a boolean if a field has been set.
func (o *Labels) HasNotes() bool {
	if o != nil && !IsNil(o.Notes) {
		return true
	}

	return false
}

// SetNotes gets a reference to the given []string and assigns it to the Notes field.
func (o *Labels) SetNotes(v []string) {
	o.Notes = v
}

// GetNumeroImmatriculation returns the NumeroImmatriculation field value if set, zero value otherwise.
func (o *Labels) GetNumeroImmatriculation() string {
	if o == nil || IsNil(o.NumeroImmatriculation) {
		var ret string
		return ret
	}
	return *o.NumeroImmatriculation
}

// GetNumeroImmatriculationOk returns a tuple with the NumeroImmatriculation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Labels) GetNumeroImmatriculationOk() (*string, bool) {
	if o == nil || IsNil(o.NumeroImmatriculation) {
		return nil, false
	}
	return o.NumeroImmatriculation, true
}

// HasNumeroImmatriculation returns a boolean if a field has been set.
func (o *Labels) HasNumeroImmatriculation() bool {
	if o != nil && !IsNil(o.NumeroImmatriculation) {
		return true
	}

	return false
}

// SetNumeroImmatriculation gets a reference to the given string and assigns it to the NumeroImmatriculation field.
func (o *Labels) SetNumeroImmatriculation(v string) {
	o.NumeroImmatriculation = &v
}

// GetInscriptions returns the Inscriptions field value if set, zero value otherwise.
func (o *Labels) GetInscriptions() []LabelsBaseInscriptionsInner {
	if o == nil || IsNil(o.Inscriptions) {
		var ret []LabelsBaseInscriptionsInner
		return ret
	}
	return o.Inscriptions
}

// GetInscriptionsOk returns a tuple with the Inscriptions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Labels) GetInscriptionsOk() ([]LabelsBaseInscriptionsInner, bool) {
	if o == nil || IsNil(o.Inscriptions) {
		return nil, false
	}
	return o.Inscriptions, true
}

// HasInscriptions returns a boolean if a field has been set.
func (o *Labels) HasInscriptions() bool {
	if o != nil && !IsNil(o.Inscriptions) {
		return true
	}

	return false
}

// SetInscriptions gets a reference to the given []LabelsBaseInscriptionsInner and assigns it to the Inscriptions field.
func (o *Labels) SetInscriptions(v []LabelsBaseInscriptionsInner) {
	o.Inscriptions = v
}

// GetMentions returns the Mentions field value if set, zero value otherwise.
func (o *Labels) GetMentions() []string {
	if o == nil || IsNil(o.Mentions) {
		var ret []string
		return ret
	}
	return o.Mentions
}

// GetMentionsOk returns a tuple with the Mentions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Labels) GetMentionsOk() ([]string, bool) {
	if o == nil || IsNil(o.Mentions) {
		return nil, false
	}
	return o.Mentions, true
}

// HasMentions returns a boolean if a field has been set.
func (o *Labels) HasMentions() bool {
	if o != nil && !IsNil(o.Mentions) {
		return true
	}

	return false
}

// SetMentions gets a reference to the given []string and assigns it to the Mentions field.
func (o *Labels) SetMentions(v []string) {
	o.Mentions = v
}

// GetNbEtablissementsConcernes returns the NbEtablissementsConcernes field value if set, zero value otherwise.
func (o *Labels) GetNbEtablissementsConcernes() int32 {
	if o == nil || IsNil(o.NbEtablissementsConcernes) {
		var ret int32
		return ret
	}
	return *o.NbEtablissementsConcernes
}

// GetNbEtablissementsConcernesOk returns a tuple with the NbEtablissementsConcernes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Labels) GetNbEtablissementsConcernesOk() (*int32, bool) {
	if o == nil || IsNil(o.NbEtablissementsConcernes) {
		return nil, false
	}
	return o.NbEtablissementsConcernes, true
}

// HasNbEtablissementsConcernes returns a boolean if a field has been set.
func (o *Labels) HasNbEtablissementsConcernes() bool {
	if o != nil && !IsNil(o.NbEtablissementsConcernes) {
		return true
	}

	return false
}

// SetNbEtablissementsConcernes gets a reference to the given int32 and assigns it to the NbEtablissementsConcernes field.
func (o *Labels) SetNbEtablissementsConcernes(v int32) {
	o.NbEtablissementsConcernes = &v
}

func (o Labels) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Labels) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Nom) {
		toSerialize["nom"] = o.Nom
	}
	if !IsNil(o.Certificats) {
		toSerialize["certificats"] = o.Certificats
	}
	if !IsNil(o.Specialites) {
		toSerialize["specialites"] = o.Specialites
	}
	if !IsNil(o.Notes) {
		toSerialize["notes"] = o.Notes
	}
	if !IsNil(o.NumeroImmatriculation) {
		toSerialize["numero_immatriculation"] = o.NumeroImmatriculation
	}
	if !IsNil(o.Inscriptions) {
		toSerialize["inscriptions"] = o.Inscriptions
	}
	if !IsNil(o.Mentions) {
		toSerialize["mentions"] = o.Mentions
	}
	if !IsNil(o.NbEtablissementsConcernes) {
		toSerialize["nb_etablissements_concernes"] = o.NbEtablissementsConcernes
	}
	return toSerialize, nil
}

type NullableLabels struct {
	value *Labels
	isSet bool
}

func (v NullableLabels) Get() *Labels {
	return v.value
}

func (v *NullableLabels) Set(val *Labels) {
	v.value = val
	v.isSet = true
}

func (v NullableLabels) IsSet() bool {
	return v.isSet
}

func (v *NullableLabels) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLabels(val *Labels) *NullableLabels {
	return &NullableLabels{value: val, isSet: true}
}

func (v NullableLabels) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLabels) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


