/*
Pappers API

L'API de Pappers vous permet de récupérer des informations et documents sur les entreprises françaises à partir de leur numéro SIREN ou SIRET.  Vous devez indiquer votre clé d'API dans les requêtes, soit via le header `api-key`, soit (déconseillé) en utilisant le paramètre query `api_token`.  L'URL d'accès à l'API est https://api.pappers.fr/v2/  Lien vers la documentation de la V3 : https://www.pappers.fr/api/documentation/v3  Lien vers la documentation de l'API internationale : https://www.pappers.in/api/documentation  L'historique des modifications (changelog) est accessible à l'url suivante : https://www.pappers.fr/api/changelog 

API version: 2.16.0
Contact: support@pappers.fr
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the EntrepriseBase type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EntrepriseBase{}

// EntrepriseBase struct for EntrepriseBase
type EntrepriseBase struct {
	// Le numéro SIREN de l'entreprise au format xxxxxxxxx.
	Siren *string `json:"siren,omitempty"`
	// Le numéro SIREN de l'entreprise au format xxx xxx xxx.
	SirenFormate *string `json:"siren_formate,omitempty"`
	// Indique si l'entreprise s'oppose à l'utilisation commerciale de ses données.
	OppositionUtilisationCommerciale *bool `json:"opposition_utilisation_commerciale,omitempty"`
	// Le nom de l'entreprise. Il est égal à sigle + dénomination en cas de personne morale, ou à nom + prénom en cas de personne physique. Nullable si le paramètre `integrer_diffusions_partielles` est à vrai.
	NomEntreprise *string `json:"nom_entreprise,omitempty"`
	// Vrai en cas de personne morale, faux en cas de personne physique.
	PersonneMorale *bool `json:"personne_morale,omitempty"`
	// Dénomination de l'entreprise si personne morale.
	Denomination *string `json:"denomination,omitempty"`
	// Nom si personne physique.
	Nom *string `json:"nom,omitempty"`
	// Prénom si personne physique.
	Prenom *string `json:"prenom,omitempty"`
	// Sexe si personne physique. F pour féminin, M pour masculin.
	Sexe *string `json:"sexe,omitempty"`
	// Code NAF de l'entreprise.
	CodeNaf *string `json:"code_naf,omitempty"`
	// Libellé du code NAF de l'entreprise.
	LibelleCodeNaf *string `json:"libelle_code_naf,omitempty"`
	// Domaine d'activité de l'entreprise.
	DomaineActivite *string `json:"domaine_activite,omitempty"`
	// Liste des conventions collectives de l'entreprise.
	ConventionsCollectives []EntrepriseBaseConventionsCollectivesInner `json:"conventions_collectives,omitempty"`
	// Date de création de l'entreprise au format AAAA-MM-JJ.
	DateCreation *string `json:"date_creation,omitempty"`
	// Date de création de l'entreprise au format JJ/MM/AAAA.
	DateCreationFormate *string `json:"date_creation_formate,omitempty"`
	// Si vrai, l'entreprise n'est plus en activité. Sinon, elle est toujours en activité.
	EntrepriseCessee *bool `json:"entreprise_cessee,omitempty"`
	// Date de cessation de l'entreprise au format AAAA-MM-JJ.
	DateCessation *string `json:"date_cessation,omitempty"`
	// Si vrai, l'entreprise a au moins un employé.
	EntrepriseEmployeuse *bool `json:"entreprise_employeuse,omitempty"`
	// Si vrai, l'entreprise est société à mission.
	SocieteAMission *bool `json:"societe_a_mission,omitempty"`
	// Catégorie juridique de l'entreprise, selon la [nomenclature Insee](https://www.insee.fr/fr/information/2028129).   **Note** : Le code correspond à celui de l'INSEE, à l'exception des SASU qui auront comme code 5720 et les EURL qui auront comme code 5498.
	CategorieJuridique *string `json:"categorie_juridique,omitempty"`
	// Forme juridique de l'entreprise.
	FormeJuridique *string `json:"forme_juridique,omitempty"`
	// Si vrai, l'entreprise est une micro-entreprise. Uniquement présent si demandé dans les champs supplémentaires.
	MicroEntreprise *bool `json:"micro_entreprise,omitempty"`
	// Forme d'exercice de l'activité principale.
	FormeExercice *string `json:"forme_exercice,omitempty"`
	// Tranche d'effectif de l'entreprise.
	Effectif *string `json:"effectif,omitempty"`
	// Effectif minimal de l'entreprise.
	EffectifMin *int32 `json:"effectif_min,omitempty"`
	// Effectif maximal de l'entreprise.
	EffectifMax *int32 `json:"effectif_max,omitempty"`
	// Tranche d'effectif de l'entreprise, selon la [nomenclature Sirene](https://www.sirene.fr/static-resources/documentation/v_sommaire_311.htm#73).
	TrancheEffectif *string `json:"tranche_effectif,omitempty"`
	// Année de validité des variables effectif, effectif_min et effectif_max.
	AnneeEffectif *int32 `json:"annee_effectif,omitempty"`
	// Capital de l'entreprise.
	Capital *float32 `json:"capital,omitempty"`
	// Statut de l'entreprise au RCS
	StatutRcs *string `json:"statut_rcs,omitempty"`
}

// NewEntrepriseBase instantiates a new EntrepriseBase object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEntrepriseBase() *EntrepriseBase {
	this := EntrepriseBase{}
	return &this
}

// NewEntrepriseBaseWithDefaults instantiates a new EntrepriseBase object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEntrepriseBaseWithDefaults() *EntrepriseBase {
	this := EntrepriseBase{}
	return &this
}

// GetSiren returns the Siren field value if set, zero value otherwise.
func (o *EntrepriseBase) GetSiren() string {
	if o == nil || IsNil(o.Siren) {
		var ret string
		return ret
	}
	return *o.Siren
}

// GetSirenOk returns a tuple with the Siren field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntrepriseBase) GetSirenOk() (*string, bool) {
	if o == nil || IsNil(o.Siren) {
		return nil, false
	}
	return o.Siren, true
}

// HasSiren returns a boolean if a field has been set.
func (o *EntrepriseBase) HasSiren() bool {
	if o != nil && !IsNil(o.Siren) {
		return true
	}

	return false
}

// SetSiren gets a reference to the given string and assigns it to the Siren field.
func (o *EntrepriseBase) SetSiren(v string) {
	o.Siren = &v
}

// GetSirenFormate returns the SirenFormate field value if set, zero value otherwise.
func (o *EntrepriseBase) GetSirenFormate() string {
	if o == nil || IsNil(o.SirenFormate) {
		var ret string
		return ret
	}
	return *o.SirenFormate
}

// GetSirenFormateOk returns a tuple with the SirenFormate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntrepriseBase) GetSirenFormateOk() (*string, bool) {
	if o == nil || IsNil(o.SirenFormate) {
		return nil, false
	}
	return o.SirenFormate, true
}

// HasSirenFormate returns a boolean if a field has been set.
func (o *EntrepriseBase) HasSirenFormate() bool {
	if o != nil && !IsNil(o.SirenFormate) {
		return true
	}

	return false
}

// SetSirenFormate gets a reference to the given string and assigns it to the SirenFormate field.
func (o *EntrepriseBase) SetSirenFormate(v string) {
	o.SirenFormate = &v
}

// GetOppositionUtilisationCommerciale returns the OppositionUtilisationCommerciale field value if set, zero value otherwise.
func (o *EntrepriseBase) GetOppositionUtilisationCommerciale() bool {
	if o == nil || IsNil(o.OppositionUtilisationCommerciale) {
		var ret bool
		return ret
	}
	return *o.OppositionUtilisationCommerciale
}

// GetOppositionUtilisationCommercialeOk returns a tuple with the OppositionUtilisationCommerciale field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntrepriseBase) GetOppositionUtilisationCommercialeOk() (*bool, bool) {
	if o == nil || IsNil(o.OppositionUtilisationCommerciale) {
		return nil, false
	}
	return o.OppositionUtilisationCommerciale, true
}

// HasOppositionUtilisationCommerciale returns a boolean if a field has been set.
func (o *EntrepriseBase) HasOppositionUtilisationCommerciale() bool {
	if o != nil && !IsNil(o.OppositionUtilisationCommerciale) {
		return true
	}

	return false
}

// SetOppositionUtilisationCommerciale gets a reference to the given bool and assigns it to the OppositionUtilisationCommerciale field.
func (o *EntrepriseBase) SetOppositionUtilisationCommerciale(v bool) {
	o.OppositionUtilisationCommerciale = &v
}

// GetNomEntreprise returns the NomEntreprise field value if set, zero value otherwise.
func (o *EntrepriseBase) GetNomEntreprise() string {
	if o == nil || IsNil(o.NomEntreprise) {
		var ret string
		return ret
	}
	return *o.NomEntreprise
}

// GetNomEntrepriseOk returns a tuple with the NomEntreprise field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntrepriseBase) GetNomEntrepriseOk() (*string, bool) {
	if o == nil || IsNil(o.NomEntreprise) {
		return nil, false
	}
	return o.NomEntreprise, true
}

// HasNomEntreprise returns a boolean if a field has been set.
func (o *EntrepriseBase) HasNomEntreprise() bool {
	if o != nil && !IsNil(o.NomEntreprise) {
		return true
	}

	return false
}

// SetNomEntreprise gets a reference to the given string and assigns it to the NomEntreprise field.
func (o *EntrepriseBase) SetNomEntreprise(v string) {
	o.NomEntreprise = &v
}

// GetPersonneMorale returns the PersonneMorale field value if set, zero value otherwise.
func (o *EntrepriseBase) GetPersonneMorale() bool {
	if o == nil || IsNil(o.PersonneMorale) {
		var ret bool
		return ret
	}
	return *o.PersonneMorale
}

// GetPersonneMoraleOk returns a tuple with the PersonneMorale field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntrepriseBase) GetPersonneMoraleOk() (*bool, bool) {
	if o == nil || IsNil(o.PersonneMorale) {
		return nil, false
	}
	return o.PersonneMorale, true
}

// HasPersonneMorale returns a boolean if a field has been set.
func (o *EntrepriseBase) HasPersonneMorale() bool {
	if o != nil && !IsNil(o.PersonneMorale) {
		return true
	}

	return false
}

// SetPersonneMorale gets a reference to the given bool and assigns it to the PersonneMorale field.
func (o *EntrepriseBase) SetPersonneMorale(v bool) {
	o.PersonneMorale = &v
}

// GetDenomination returns the Denomination field value if set, zero value otherwise.
func (o *EntrepriseBase) GetDenomination() string {
	if o == nil || IsNil(o.Denomination) {
		var ret string
		return ret
	}
	return *o.Denomination
}

// GetDenominationOk returns a tuple with the Denomination field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntrepriseBase) GetDenominationOk() (*string, bool) {
	if o == nil || IsNil(o.Denomination) {
		return nil, false
	}
	return o.Denomination, true
}

// HasDenomination returns a boolean if a field has been set.
func (o *EntrepriseBase) HasDenomination() bool {
	if o != nil && !IsNil(o.Denomination) {
		return true
	}

	return false
}

// SetDenomination gets a reference to the given string and assigns it to the Denomination field.
func (o *EntrepriseBase) SetDenomination(v string) {
	o.Denomination = &v
}

// GetNom returns the Nom field value if set, zero value otherwise.
func (o *EntrepriseBase) GetNom() string {
	if o == nil || IsNil(o.Nom) {
		var ret string
		return ret
	}
	return *o.Nom
}

// GetNomOk returns a tuple with the Nom field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntrepriseBase) GetNomOk() (*string, bool) {
	if o == nil || IsNil(o.Nom) {
		return nil, false
	}
	return o.Nom, true
}

// HasNom returns a boolean if a field has been set.
func (o *EntrepriseBase) HasNom() bool {
	if o != nil && !IsNil(o.Nom) {
		return true
	}

	return false
}

// SetNom gets a reference to the given string and assigns it to the Nom field.
func (o *EntrepriseBase) SetNom(v string) {
	o.Nom = &v
}

// GetPrenom returns the Prenom field value if set, zero value otherwise.
func (o *EntrepriseBase) GetPrenom() string {
	if o == nil || IsNil(o.Prenom) {
		var ret string
		return ret
	}
	return *o.Prenom
}

// GetPrenomOk returns a tuple with the Prenom field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntrepriseBase) GetPrenomOk() (*string, bool) {
	if o == nil || IsNil(o.Prenom) {
		return nil, false
	}
	return o.Prenom, true
}

// HasPrenom returns a boolean if a field has been set.
func (o *EntrepriseBase) HasPrenom() bool {
	if o != nil && !IsNil(o.Prenom) {
		return true
	}

	return false
}

// SetPrenom gets a reference to the given string and assigns it to the Prenom field.
func (o *EntrepriseBase) SetPrenom(v string) {
	o.Prenom = &v
}

// GetSexe returns the Sexe field value if set, zero value otherwise.
func (o *EntrepriseBase) GetSexe() string {
	if o == nil || IsNil(o.Sexe) {
		var ret string
		return ret
	}
	return *o.Sexe
}

// GetSexeOk returns a tuple with the Sexe field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntrepriseBase) GetSexeOk() (*string, bool) {
	if o == nil || IsNil(o.Sexe) {
		return nil, false
	}
	return o.Sexe, true
}

// HasSexe returns a boolean if a field has been set.
func (o *EntrepriseBase) HasSexe() bool {
	if o != nil && !IsNil(o.Sexe) {
		return true
	}

	return false
}

// SetSexe gets a reference to the given string and assigns it to the Sexe field.
func (o *EntrepriseBase) SetSexe(v string) {
	o.Sexe = &v
}

// GetCodeNaf returns the CodeNaf field value if set, zero value otherwise.
func (o *EntrepriseBase) GetCodeNaf() string {
	if o == nil || IsNil(o.CodeNaf) {
		var ret string
		return ret
	}
	return *o.CodeNaf
}

// GetCodeNafOk returns a tuple with the CodeNaf field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntrepriseBase) GetCodeNafOk() (*string, bool) {
	if o == nil || IsNil(o.CodeNaf) {
		return nil, false
	}
	return o.CodeNaf, true
}

// HasCodeNaf returns a boolean if a field has been set.
func (o *EntrepriseBase) HasCodeNaf() bool {
	if o != nil && !IsNil(o.CodeNaf) {
		return true
	}

	return false
}

// SetCodeNaf gets a reference to the given string and assigns it to the CodeNaf field.
func (o *EntrepriseBase) SetCodeNaf(v string) {
	o.CodeNaf = &v
}

// GetLibelleCodeNaf returns the LibelleCodeNaf field value if set, zero value otherwise.
func (o *EntrepriseBase) GetLibelleCodeNaf() string {
	if o == nil || IsNil(o.LibelleCodeNaf) {
		var ret string
		return ret
	}
	return *o.LibelleCodeNaf
}

// GetLibelleCodeNafOk returns a tuple with the LibelleCodeNaf field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntrepriseBase) GetLibelleCodeNafOk() (*string, bool) {
	if o == nil || IsNil(o.LibelleCodeNaf) {
		return nil, false
	}
	return o.LibelleCodeNaf, true
}

// HasLibelleCodeNaf returns a boolean if a field has been set.
func (o *EntrepriseBase) HasLibelleCodeNaf() bool {
	if o != nil && !IsNil(o.LibelleCodeNaf) {
		return true
	}

	return false
}

// SetLibelleCodeNaf gets a reference to the given string and assigns it to the LibelleCodeNaf field.
func (o *EntrepriseBase) SetLibelleCodeNaf(v string) {
	o.LibelleCodeNaf = &v
}

// GetDomaineActivite returns the DomaineActivite field value if set, zero value otherwise.
func (o *EntrepriseBase) GetDomaineActivite() string {
	if o == nil || IsNil(o.DomaineActivite) {
		var ret string
		return ret
	}
	return *o.DomaineActivite
}

// GetDomaineActiviteOk returns a tuple with the DomaineActivite field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntrepriseBase) GetDomaineActiviteOk() (*string, bool) {
	if o == nil || IsNil(o.DomaineActivite) {
		return nil, false
	}
	return o.DomaineActivite, true
}

// HasDomaineActivite returns a boolean if a field has been set.
func (o *EntrepriseBase) HasDomaineActivite() bool {
	if o != nil && !IsNil(o.DomaineActivite) {
		return true
	}

	return false
}

// SetDomaineActivite gets a reference to the given string and assigns it to the DomaineActivite field.
func (o *EntrepriseBase) SetDomaineActivite(v string) {
	o.DomaineActivite = &v
}

// GetConventionsCollectives returns the ConventionsCollectives field value if set, zero value otherwise.
func (o *EntrepriseBase) GetConventionsCollectives() []EntrepriseBaseConventionsCollectivesInner {
	if o == nil || IsNil(o.ConventionsCollectives) {
		var ret []EntrepriseBaseConventionsCollectivesInner
		return ret
	}
	return o.ConventionsCollectives
}

// GetConventionsCollectivesOk returns a tuple with the ConventionsCollectives field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntrepriseBase) GetConventionsCollectivesOk() ([]EntrepriseBaseConventionsCollectivesInner, bool) {
	if o == nil || IsNil(o.ConventionsCollectives) {
		return nil, false
	}
	return o.ConventionsCollectives, true
}

// HasConventionsCollectives returns a boolean if a field has been set.
func (o *EntrepriseBase) HasConventionsCollectives() bool {
	if o != nil && !IsNil(o.ConventionsCollectives) {
		return true
	}

	return false
}

// SetConventionsCollectives gets a reference to the given []EntrepriseBaseConventionsCollectivesInner and assigns it to the ConventionsCollectives field.
func (o *EntrepriseBase) SetConventionsCollectives(v []EntrepriseBaseConventionsCollectivesInner) {
	o.ConventionsCollectives = v
}

// GetDateCreation returns the DateCreation field value if set, zero value otherwise.
func (o *EntrepriseBase) GetDateCreation() string {
	if o == nil || IsNil(o.DateCreation) {
		var ret string
		return ret
	}
	return *o.DateCreation
}

// GetDateCreationOk returns a tuple with the DateCreation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntrepriseBase) GetDateCreationOk() (*string, bool) {
	if o == nil || IsNil(o.DateCreation) {
		return nil, false
	}
	return o.DateCreation, true
}

// HasDateCreation returns a boolean if a field has been set.
func (o *EntrepriseBase) HasDateCreation() bool {
	if o != nil && !IsNil(o.DateCreation) {
		return true
	}

	return false
}

// SetDateCreation gets a reference to the given string and assigns it to the DateCreation field.
func (o *EntrepriseBase) SetDateCreation(v string) {
	o.DateCreation = &v
}

// GetDateCreationFormate returns the DateCreationFormate field value if set, zero value otherwise.
func (o *EntrepriseBase) GetDateCreationFormate() string {
	if o == nil || IsNil(o.DateCreationFormate) {
		var ret string
		return ret
	}
	return *o.DateCreationFormate
}

// GetDateCreationFormateOk returns a tuple with the DateCreationFormate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntrepriseBase) GetDateCreationFormateOk() (*string, bool) {
	if o == nil || IsNil(o.DateCreationFormate) {
		return nil, false
	}
	return o.DateCreationFormate, true
}

// HasDateCreationFormate returns a boolean if a field has been set.
func (o *EntrepriseBase) HasDateCreationFormate() bool {
	if o != nil && !IsNil(o.DateCreationFormate) {
		return true
	}

	return false
}

// SetDateCreationFormate gets a reference to the given string and assigns it to the DateCreationFormate field.
func (o *EntrepriseBase) SetDateCreationFormate(v string) {
	o.DateCreationFormate = &v
}

// GetEntrepriseCessee returns the EntrepriseCessee field value if set, zero value otherwise.
func (o *EntrepriseBase) GetEntrepriseCessee() bool {
	if o == nil || IsNil(o.EntrepriseCessee) {
		var ret bool
		return ret
	}
	return *o.EntrepriseCessee
}

// GetEntrepriseCesseeOk returns a tuple with the EntrepriseCessee field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntrepriseBase) GetEntrepriseCesseeOk() (*bool, bool) {
	if o == nil || IsNil(o.EntrepriseCessee) {
		return nil, false
	}
	return o.EntrepriseCessee, true
}

// HasEntrepriseCessee returns a boolean if a field has been set.
func (o *EntrepriseBase) HasEntrepriseCessee() bool {
	if o != nil && !IsNil(o.EntrepriseCessee) {
		return true
	}

	return false
}

// SetEntrepriseCessee gets a reference to the given bool and assigns it to the EntrepriseCessee field.
func (o *EntrepriseBase) SetEntrepriseCessee(v bool) {
	o.EntrepriseCessee = &v
}

// GetDateCessation returns the DateCessation field value if set, zero value otherwise.
func (o *EntrepriseBase) GetDateCessation() string {
	if o == nil || IsNil(o.DateCessation) {
		var ret string
		return ret
	}
	return *o.DateCessation
}

// GetDateCessationOk returns a tuple with the DateCessation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntrepriseBase) GetDateCessationOk() (*string, bool) {
	if o == nil || IsNil(o.DateCessation) {
		return nil, false
	}
	return o.DateCessation, true
}

// HasDateCessation returns a boolean if a field has been set.
func (o *EntrepriseBase) HasDateCessation() bool {
	if o != nil && !IsNil(o.DateCessation) {
		return true
	}

	return false
}

// SetDateCessation gets a reference to the given string and assigns it to the DateCessation field.
func (o *EntrepriseBase) SetDateCessation(v string) {
	o.DateCessation = &v
}

// GetEntrepriseEmployeuse returns the EntrepriseEmployeuse field value if set, zero value otherwise.
func (o *EntrepriseBase) GetEntrepriseEmployeuse() bool {
	if o == nil || IsNil(o.EntrepriseEmployeuse) {
		var ret bool
		return ret
	}
	return *o.EntrepriseEmployeuse
}

// GetEntrepriseEmployeuseOk returns a tuple with the EntrepriseEmployeuse field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntrepriseBase) GetEntrepriseEmployeuseOk() (*bool, bool) {
	if o == nil || IsNil(o.EntrepriseEmployeuse) {
		return nil, false
	}
	return o.EntrepriseEmployeuse, true
}

// HasEntrepriseEmployeuse returns a boolean if a field has been set.
func (o *EntrepriseBase) HasEntrepriseEmployeuse() bool {
	if o != nil && !IsNil(o.EntrepriseEmployeuse) {
		return true
	}

	return false
}

// SetEntrepriseEmployeuse gets a reference to the given bool and assigns it to the EntrepriseEmployeuse field.
func (o *EntrepriseBase) SetEntrepriseEmployeuse(v bool) {
	o.EntrepriseEmployeuse = &v
}

// GetSocieteAMission returns the SocieteAMission field value if set, zero value otherwise.
func (o *EntrepriseBase) GetSocieteAMission() bool {
	if o == nil || IsNil(o.SocieteAMission) {
		var ret bool
		return ret
	}
	return *o.SocieteAMission
}

// GetSocieteAMissionOk returns a tuple with the SocieteAMission field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntrepriseBase) GetSocieteAMissionOk() (*bool, bool) {
	if o == nil || IsNil(o.SocieteAMission) {
		return nil, false
	}
	return o.SocieteAMission, true
}

// HasSocieteAMission returns a boolean if a field has been set.
func (o *EntrepriseBase) HasSocieteAMission() bool {
	if o != nil && !IsNil(o.SocieteAMission) {
		return true
	}

	return false
}

// SetSocieteAMission gets a reference to the given bool and assigns it to the SocieteAMission field.
func (o *EntrepriseBase) SetSocieteAMission(v bool) {
	o.SocieteAMission = &v
}

// GetCategorieJuridique returns the CategorieJuridique field value if set, zero value otherwise.
func (o *EntrepriseBase) GetCategorieJuridique() string {
	if o == nil || IsNil(o.CategorieJuridique) {
		var ret string
		return ret
	}
	return *o.CategorieJuridique
}

// GetCategorieJuridiqueOk returns a tuple with the CategorieJuridique field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntrepriseBase) GetCategorieJuridiqueOk() (*string, bool) {
	if o == nil || IsNil(o.CategorieJuridique) {
		return nil, false
	}
	return o.CategorieJuridique, true
}

// HasCategorieJuridique returns a boolean if a field has been set.
func (o *EntrepriseBase) HasCategorieJuridique() bool {
	if o != nil && !IsNil(o.CategorieJuridique) {
		return true
	}

	return false
}

// SetCategorieJuridique gets a reference to the given string and assigns it to the CategorieJuridique field.
func (o *EntrepriseBase) SetCategorieJuridique(v string) {
	o.CategorieJuridique = &v
}

// GetFormeJuridique returns the FormeJuridique field value if set, zero value otherwise.
func (o *EntrepriseBase) GetFormeJuridique() string {
	if o == nil || IsNil(o.FormeJuridique) {
		var ret string
		return ret
	}
	return *o.FormeJuridique
}

// GetFormeJuridiqueOk returns a tuple with the FormeJuridique field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntrepriseBase) GetFormeJuridiqueOk() (*string, bool) {
	if o == nil || IsNil(o.FormeJuridique) {
		return nil, false
	}
	return o.FormeJuridique, true
}

// HasFormeJuridique returns a boolean if a field has been set.
func (o *EntrepriseBase) HasFormeJuridique() bool {
	if o != nil && !IsNil(o.FormeJuridique) {
		return true
	}

	return false
}

// SetFormeJuridique gets a reference to the given string and assigns it to the FormeJuridique field.
func (o *EntrepriseBase) SetFormeJuridique(v string) {
	o.FormeJuridique = &v
}

// GetMicroEntreprise returns the MicroEntreprise field value if set, zero value otherwise.
func (o *EntrepriseBase) GetMicroEntreprise() bool {
	if o == nil || IsNil(o.MicroEntreprise) {
		var ret bool
		return ret
	}
	return *o.MicroEntreprise
}

// GetMicroEntrepriseOk returns a tuple with the MicroEntreprise field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntrepriseBase) GetMicroEntrepriseOk() (*bool, bool) {
	if o == nil || IsNil(o.MicroEntreprise) {
		return nil, false
	}
	return o.MicroEntreprise, true
}

// HasMicroEntreprise returns a boolean if a field has been set.
func (o *EntrepriseBase) HasMicroEntreprise() bool {
	if o != nil && !IsNil(o.MicroEntreprise) {
		return true
	}

	return false
}

// SetMicroEntreprise gets a reference to the given bool and assigns it to the MicroEntreprise field.
func (o *EntrepriseBase) SetMicroEntreprise(v bool) {
	o.MicroEntreprise = &v
}

// GetFormeExercice returns the FormeExercice field value if set, zero value otherwise.
func (o *EntrepriseBase) GetFormeExercice() string {
	if o == nil || IsNil(o.FormeExercice) {
		var ret string
		return ret
	}
	return *o.FormeExercice
}

// GetFormeExerciceOk returns a tuple with the FormeExercice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntrepriseBase) GetFormeExerciceOk() (*string, bool) {
	if o == nil || IsNil(o.FormeExercice) {
		return nil, false
	}
	return o.FormeExercice, true
}

// HasFormeExercice returns a boolean if a field has been set.
func (o *EntrepriseBase) HasFormeExercice() bool {
	if o != nil && !IsNil(o.FormeExercice) {
		return true
	}

	return false
}

// SetFormeExercice gets a reference to the given string and assigns it to the FormeExercice field.
func (o *EntrepriseBase) SetFormeExercice(v string) {
	o.FormeExercice = &v
}

// GetEffectif returns the Effectif field value if set, zero value otherwise.
func (o *EntrepriseBase) GetEffectif() string {
	if o == nil || IsNil(o.Effectif) {
		var ret string
		return ret
	}
	return *o.Effectif
}

// GetEffectifOk returns a tuple with the Effectif field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntrepriseBase) GetEffectifOk() (*string, bool) {
	if o == nil || IsNil(o.Effectif) {
		return nil, false
	}
	return o.Effectif, true
}

// HasEffectif returns a boolean if a field has been set.
func (o *EntrepriseBase) HasEffectif() bool {
	if o != nil && !IsNil(o.Effectif) {
		return true
	}

	return false
}

// SetEffectif gets a reference to the given string and assigns it to the Effectif field.
func (o *EntrepriseBase) SetEffectif(v string) {
	o.Effectif = &v
}

// GetEffectifMin returns the EffectifMin field value if set, zero value otherwise.
func (o *EntrepriseBase) GetEffectifMin() int32 {
	if o == nil || IsNil(o.EffectifMin) {
		var ret int32
		return ret
	}
	return *o.EffectifMin
}

// GetEffectifMinOk returns a tuple with the EffectifMin field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntrepriseBase) GetEffectifMinOk() (*int32, bool) {
	if o == nil || IsNil(o.EffectifMin) {
		return nil, false
	}
	return o.EffectifMin, true
}

// HasEffectifMin returns a boolean if a field has been set.
func (o *EntrepriseBase) HasEffectifMin() bool {
	if o != nil && !IsNil(o.EffectifMin) {
		return true
	}

	return false
}

// SetEffectifMin gets a reference to the given int32 and assigns it to the EffectifMin field.
func (o *EntrepriseBase) SetEffectifMin(v int32) {
	o.EffectifMin = &v
}

// GetEffectifMax returns the EffectifMax field value if set, zero value otherwise.
func (o *EntrepriseBase) GetEffectifMax() int32 {
	if o == nil || IsNil(o.EffectifMax) {
		var ret int32
		return ret
	}
	return *o.EffectifMax
}

// GetEffectifMaxOk returns a tuple with the EffectifMax field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntrepriseBase) GetEffectifMaxOk() (*int32, bool) {
	if o == nil || IsNil(o.EffectifMax) {
		return nil, false
	}
	return o.EffectifMax, true
}

// HasEffectifMax returns a boolean if a field has been set.
func (o *EntrepriseBase) HasEffectifMax() bool {
	if o != nil && !IsNil(o.EffectifMax) {
		return true
	}

	return false
}

// SetEffectifMax gets a reference to the given int32 and assigns it to the EffectifMax field.
func (o *EntrepriseBase) SetEffectifMax(v int32) {
	o.EffectifMax = &v
}

// GetTrancheEffectif returns the TrancheEffectif field value if set, zero value otherwise.
func (o *EntrepriseBase) GetTrancheEffectif() string {
	if o == nil || IsNil(o.TrancheEffectif) {
		var ret string
		return ret
	}
	return *o.TrancheEffectif
}

// GetTrancheEffectifOk returns a tuple with the TrancheEffectif field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntrepriseBase) GetTrancheEffectifOk() (*string, bool) {
	if o == nil || IsNil(o.TrancheEffectif) {
		return nil, false
	}
	return o.TrancheEffectif, true
}

// HasTrancheEffectif returns a boolean if a field has been set.
func (o *EntrepriseBase) HasTrancheEffectif() bool {
	if o != nil && !IsNil(o.TrancheEffectif) {
		return true
	}

	return false
}

// SetTrancheEffectif gets a reference to the given string and assigns it to the TrancheEffectif field.
func (o *EntrepriseBase) SetTrancheEffectif(v string) {
	o.TrancheEffectif = &v
}

// GetAnneeEffectif returns the AnneeEffectif field value if set, zero value otherwise.
func (o *EntrepriseBase) GetAnneeEffectif() int32 {
	if o == nil || IsNil(o.AnneeEffectif) {
		var ret int32
		return ret
	}
	return *o.AnneeEffectif
}

// GetAnneeEffectifOk returns a tuple with the AnneeEffectif field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntrepriseBase) GetAnneeEffectifOk() (*int32, bool) {
	if o == nil || IsNil(o.AnneeEffectif) {
		return nil, false
	}
	return o.AnneeEffectif, true
}

// HasAnneeEffectif returns a boolean if a field has been set.
func (o *EntrepriseBase) HasAnneeEffectif() bool {
	if o != nil && !IsNil(o.AnneeEffectif) {
		return true
	}

	return false
}

// SetAnneeEffectif gets a reference to the given int32 and assigns it to the AnneeEffectif field.
func (o *EntrepriseBase) SetAnneeEffectif(v int32) {
	o.AnneeEffectif = &v
}

// GetCapital returns the Capital field value if set, zero value otherwise.
func (o *EntrepriseBase) GetCapital() float32 {
	if o == nil || IsNil(o.Capital) {
		var ret float32
		return ret
	}
	return *o.Capital
}

// GetCapitalOk returns a tuple with the Capital field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntrepriseBase) GetCapitalOk() (*float32, bool) {
	if o == nil || IsNil(o.Capital) {
		return nil, false
	}
	return o.Capital, true
}

// HasCapital returns a boolean if a field has been set.
func (o *EntrepriseBase) HasCapital() bool {
	if o != nil && !IsNil(o.Capital) {
		return true
	}

	return false
}

// SetCapital gets a reference to the given float32 and assigns it to the Capital field.
func (o *EntrepriseBase) SetCapital(v float32) {
	o.Capital = &v
}

// GetStatutRcs returns the StatutRcs field value if set, zero value otherwise.
func (o *EntrepriseBase) GetStatutRcs() string {
	if o == nil || IsNil(o.StatutRcs) {
		var ret string
		return ret
	}
	return *o.StatutRcs
}

// GetStatutRcsOk returns a tuple with the StatutRcs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntrepriseBase) GetStatutRcsOk() (*string, bool) {
	if o == nil || IsNil(o.StatutRcs) {
		return nil, false
	}
	return o.StatutRcs, true
}

// HasStatutRcs returns a boolean if a field has been set.
func (o *EntrepriseBase) HasStatutRcs() bool {
	if o != nil && !IsNil(o.StatutRcs) {
		return true
	}

	return false
}

// SetStatutRcs gets a reference to the given string and assigns it to the StatutRcs field.
func (o *EntrepriseBase) SetStatutRcs(v string) {
	o.StatutRcs = &v
}

func (o EntrepriseBase) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EntrepriseBase) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Siren) {
		toSerialize["siren"] = o.Siren
	}
	if !IsNil(o.SirenFormate) {
		toSerialize["siren_formate"] = o.SirenFormate
	}
	if !IsNil(o.OppositionUtilisationCommerciale) {
		toSerialize["opposition_utilisation_commerciale"] = o.OppositionUtilisationCommerciale
	}
	if !IsNil(o.NomEntreprise) {
		toSerialize["nom_entreprise"] = o.NomEntreprise
	}
	if !IsNil(o.PersonneMorale) {
		toSerialize["personne_morale"] = o.PersonneMorale
	}
	if !IsNil(o.Denomination) {
		toSerialize["denomination"] = o.Denomination
	}
	if !IsNil(o.Nom) {
		toSerialize["nom"] = o.Nom
	}
	if !IsNil(o.Prenom) {
		toSerialize["prenom"] = o.Prenom
	}
	if !IsNil(o.Sexe) {
		toSerialize["sexe"] = o.Sexe
	}
	if !IsNil(o.CodeNaf) {
		toSerialize["code_naf"] = o.CodeNaf
	}
	if !IsNil(o.LibelleCodeNaf) {
		toSerialize["libelle_code_naf"] = o.LibelleCodeNaf
	}
	if !IsNil(o.DomaineActivite) {
		toSerialize["domaine_activite"] = o.DomaineActivite
	}
	if !IsNil(o.ConventionsCollectives) {
		toSerialize["conventions_collectives"] = o.ConventionsCollectives
	}
	if !IsNil(o.DateCreation) {
		toSerialize["date_creation"] = o.DateCreation
	}
	if !IsNil(o.DateCreationFormate) {
		toSerialize["date_creation_formate"] = o.DateCreationFormate
	}
	if !IsNil(o.EntrepriseCessee) {
		toSerialize["entreprise_cessee"] = o.EntrepriseCessee
	}
	if !IsNil(o.DateCessation) {
		toSerialize["date_cessation"] = o.DateCessation
	}
	if !IsNil(o.EntrepriseEmployeuse) {
		toSerialize["entreprise_employeuse"] = o.EntrepriseEmployeuse
	}
	if !IsNil(o.SocieteAMission) {
		toSerialize["societe_a_mission"] = o.SocieteAMission
	}
	if !IsNil(o.CategorieJuridique) {
		toSerialize["categorie_juridique"] = o.CategorieJuridique
	}
	if !IsNil(o.FormeJuridique) {
		toSerialize["forme_juridique"] = o.FormeJuridique
	}
	if !IsNil(o.MicroEntreprise) {
		toSerialize["micro_entreprise"] = o.MicroEntreprise
	}
	if !IsNil(o.FormeExercice) {
		toSerialize["forme_exercice"] = o.FormeExercice
	}
	if !IsNil(o.Effectif) {
		toSerialize["effectif"] = o.Effectif
	}
	if !IsNil(o.EffectifMin) {
		toSerialize["effectif_min"] = o.EffectifMin
	}
	if !IsNil(o.EffectifMax) {
		toSerialize["effectif_max"] = o.EffectifMax
	}
	if !IsNil(o.TrancheEffectif) {
		toSerialize["tranche_effectif"] = o.TrancheEffectif
	}
	if !IsNil(o.AnneeEffectif) {
		toSerialize["annee_effectif"] = o.AnneeEffectif
	}
	if !IsNil(o.Capital) {
		toSerialize["capital"] = o.Capital
	}
	if !IsNil(o.StatutRcs) {
		toSerialize["statut_rcs"] = o.StatutRcs
	}
	return toSerialize, nil
}

type NullableEntrepriseBase struct {
	value *EntrepriseBase
	isSet bool
}

func (v NullableEntrepriseBase) Get() *EntrepriseBase {
	return v.value
}

func (v *NullableEntrepriseBase) Set(val *EntrepriseBase) {
	v.value = val
	v.isSet = true
}

func (v NullableEntrepriseBase) IsSet() bool {
	return v.isSet
}

func (v *NullableEntrepriseBase) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEntrepriseBase(val *EntrepriseBase) *NullableEntrepriseBase {
	return &NullableEntrepriseBase{value: val, isSet: true}
}

func (v NullableEntrepriseBase) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEntrepriseBase) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


